# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 13, 18, 56, 54117, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
